# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

name: app
type: 'nodejs:22'
disk: 5120
size: L
resources:
    base_memory: 1024
    memory_ratio: 1024
dependencies:
    nodejs:
        pnpm: "10.6.5"
mounts:
    '/core/.next':
        source: local
        source_path: 'next'
    '/core/build-config':
        source: local
        source_path: 'build-config'
    '/core/messages':
        source: local
        source_path: 'messages'
web:
    locations:
        '/':
            root: 'core'
            request_buffering:
                enabled: false
            headers:
                X-Frame-Options: SAMEORIGIN
    commands:
        start: cd /app/core && NODE_ENV=production pnpm exec next start -p $PORT
build:
    flavor: none
hooks:
    build: |
        set -eu
        chmod +x scripts/setup_env_vars.sh
        chmod +x scripts/setup_mounts.sh
        ./scripts/setup_env_vars.sh
        pnpm install
        NODE_OPTIONS="--max-old-space-size=8192" pnpm build
        ./scripts/setup_mounts.sh
    deploy: |
        set -eu
        ./scripts/setup_mounts.sh
