# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

name: app
type: 'nodejs:22'
disk: 5120
size: L
resources:
    base_memory: 1024
    memory_ratio: 1024
dependencies:
    nodejs:
        pnpm: "10.6.5"
mounts:
    '/core':
        source: local
        source_path: '.next/standalone/core'
    '/core/build-config':
        source: local
        source_path: 'build-config'
    '/core/messages':
        source: local
        source_path: 'messages'
web:
    locations:
        '/':
            root: 'core'
            scripts: false
            passthru: true
            request_buffering:
                enabled: false
            headers:
                X-Frame-Options: SAMEORIGIN
    commands:
        start: cd /app/core && NODE_ENV=production node .next/standalone/core/server.js
build:
    flavor: none
hooks:
    build: |
        set -eu
        chmod +x scripts/setup_env_vars.sh
        chmod +x scripts/setup_mounts.sh
        ./scripts/setup_env_vars.sh
        pnpm install
        NODE_OPTIONS="--max-old-space-size=8192" pnpm build
        cp /app/core/.env.local /app/core/.next/standalone/core/.env.local
        cp -r /app/core/.next/static /app/core/.next/standalone/core/.next/
        ./scripts/setup_mounts.sh
    deploy: |
        set -eu
        ./scripts/setup_mounts.sh
