#!/usr/bin/env bash

echo "Setting up environment variables..."

ROOT_ENV_FILE="/app/.env.local"
touch $ROOT_ENV_FILE
echo "BIGCOMMERCE_STORE_HASH=$BIGCOMMERCE_STORE_HASH" > $ROOT_ENV_FILE
echo "BIGCOMMERCE_STOREFRONT_TOKEN=$BIGCOMMERCE_STOREFRONT_TOKEN" >> $ROOT_ENV_FILE
echo "BIGCOMMERCE_CHANNEL_ID=$BIGCOMMERCE_CHANNEL_ID" >> $ROOT_ENV_FILE
echo "ENABLE_ADMIN_ROUTE=$ENABLE_ADMIN_ROUTE" >> $ROOT_ENV_FILE
echo "AUTH_SECRET=$AUTH_SECRET" >> $ROOT_ENV_FILE
echo "AUTH_URL=$AUTH_URL" >> $ROOT_ENV_FILE
echo "TURBO_REMOTE_CACHE_SIGNATURE_KEY=$TURBO_REMOTE_CACHE_SIGNATURE_KEY" >> $ROOT_ENV_FILE
echo "DEFAULT_REVALIDATE_TARGET=$DEFAULT_REVALIDATE_TARGET" >> $ROOT_ENV_FILE
echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> $ROOT_ENV_FILE
echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> $ROOT_ENV_FILE
echo "CONTENTFUL_PREVIEW_ACCESS_TOKEN=$CONTENTFUL_PREVIEW_ACCESS_TOKEN" >> $ROOT_ENV_FILE
echo "CONTENTFUL_ENVIRONMENT=$CONTENTFUL_ENVIRONMENT" >> $ROOT_ENV_FILE
echo ".env.local file created"

echo "Environment variables set"
