#!/usr/bin/env bash

echo "Setting up environment variables"

ENV_FILE="/app/core/.env.local"
touch $ENV_FILE

echo "BIGCOMMERCE_STORE_HASH=$BIGCOMMERCE_STORE_HASH" > $ENV_FILE
echo "BIGCOMMERCE_STOREFRONT_TOKEN=$BIGCOMMERCE_STOREFRONT_TOKEN" >> $ENV_FILE
echo "BIGCOMMERCE_CHANNEL_ID=$BIGCOMMERCE_CHANNEL_ID" >> $ENV_FILE
echo "ENABLE_ADMIN_ROUTE=$ENABLE_ADMIN_ROUTE" >> $ENV_FILE
echo "AUTH_SECRET=$AUTH_SECRET" >> $ENV_FILE
echo "AUTH_TRUST_HOST=$AUTH_TRUST_HOST" >> $ENV_FILE
echo "TURBO_REMOTE_CACHE_SIGNATURE_KEY=$TURBO_REMOTE_CACHE_SIGNATURE_KEY" >> $ENV_FILE
echo "DEFAULT_REVALIDATE_TARGET=$DEFAULT_REVALIDATE_TARGET" >> $ENV_FILE

echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> $ENV_FILE
echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> $ENV_FILE
echo "CONTENTFUL_PREVIEW_ACCESS_TOKEN=$CONTENTFUL_PREVIEW_ACCESS_TOKEN" >> $ENV_FILE
echo "CONTENTFUL_ENVIRONMENT=$CONTENTFUL_ENVIRONMENT" >> $ENV_FILE

echo "NEXT_PUBLIC_ALGOLIA_APP_ID=$NEXT_PUBLIC_ALGOLIA_APP_ID" >> $ENV_FILE
echo "NEXT_PUBLIC_ALGOLIA_API_KEY=$NEXT_PUBLIC_ALGOLIA_API_KEY" >> $ENV_FILE
echo "NEXT_PUBLIC_ALGOLIA_INDEX_NAME=$NEXT_PUBLIC_ALGOLIA_INDEX_NAME" >> $ENV_FILE

echo "Environment variables set"
